name: Build Flask app

on:
  push:
    branches:
      - master

jobs:
  build_app:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Print branch information
        run: echo "Now building branch ${{ github.ref }}."

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
