name: Build Flask app

on:
  push:
    branches:
      - master

jobs:
  build_app:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Print branch information
        run: echo "Now building branch ${{ github.ref }}."

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: 01_Flask_Docker_App/
          push: true
          tags: |
            eugeneromero/uis-demo-flask-app:${{ github.run_id }}
            eugeneromero/uis-demo-flask-app:latest
